version: '3.9'

services:
    laravel-app:
        # urnau/php82-app-2023:horizon
        # container_name: laravel-app
        image: laravel-octane
        build:
            context: .
            dockerfile: Dockerfile
#        ports:
#            - "8081:80" #http
#            - "8443:443" #https
        networks:
            - traefik_public
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.laravel-app.rule=Host(`app.laravix.com.br`)"
                - "traefik.http.services.laravel-app.loadbalancer.server.port=80"
                - "traefik.http.routers.laravel-app.service=laravel-app"
                - "traefik.http.routers.laravel-app.entrypoints=https"
                - "traefik.http.routers.laravel-app.tls=true"
            replicas: 1
            resources:
                reservations:
                    cpus: "1"
                    memory: 3G
            restart_policy:
                condition: on-failure

    mysql:
        image: mysql:8.0
        hostname: mysql.laravix.com.br
        networks:
            traefik_public:
                aliases:
                    - mysql.laravix.com.br
        deploy:
            labels:
                - "traefik.enable=false"
        environment:
            MYSQL_ROOT_PASSWORD: WQksBRFpeK6W
            MYSQL_DATABASE: laravel_api_trainee
            MYSQL_USER: postgres
            MYSQL_PASSWORD: WQksBRFpeK6W
        volumes:
            - mysql-data:/var/lib/mysql
        restart: always

volumes:
    mysql-data:

networks:
    traefik_public:
        external: true
